---
editor: visual
---

Research plays a central role in my teaching as students improve their analytical skills and master core concepts of geography through hands-on experience.I have been a teaching assistant for courses that focus on research, geography, statistics, and sustainability.

### **Penn State University**

[*Graduate Teaching Assistant*]{.underline}

-   **The Pennsylvania State University Department of Geography** *(2023)*

GEOG 464: Advanced Spatial Analysis

-   **The Pennsylvania State University Department of Geography** *(2023)*

GEOG 361: Cartography

-   **The Pennsylvania State University Department of Geography** *(2022)*

GEOG 364: Spatial Analysis

[*Undergraduate Teaching Assistant*]{.underline}

-   **The Pennsylvania State University College of Earth and Mineral Sciences** *(2021)*

EMSC 100S: What is Sustainability?

-   **The Pennsylvania State University Department of Geography** *(2020 & 2021)*

GEOG 301: Thinking Geographically

-   **The Pennsylvania State University Department of Geography** *(2020)*

GEOG 364: Spatial Analysis
